export enum IconNameEnum {
  BUILDING = 'BUILDING',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  MORE = 'MORE',
  LOGO = 'LOGO',
  LINKEDIN = 'LINKEDIN',
  TWITTER = 'TWITTER',
  FACEBOOK = 'FACEBOOK',
  MENU = 'MENU',
  CARET = 'CARET',
  LINK = 'LINK'
}
